import { APIHeroProvider } from "@apihero/react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useGetRepo } from "./apihero/github";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Stars</h1>

        <APIHeroProvider projectKey="cl99z315o16093f6gdx7d1to9u">
          <Stars />
        </APIHeroProvider>
      </main>
    </div>
  );
}

function Stars() {
  const result = useGetRepo({
    owner: "Infisical",
    repo: "infisical-cli",
  });

  const { data, status, error } = result;

  return (
    <>
      {status === "loading" ? (
        <div>Loading...</div>
      ) : status === "error" ? (
        <div>{error.message}</div>
      ) : (
        <h1 className={styles.title}>{data.stargazers_count}</h1>
      )}
    </>
  );
}
